-- ==========================================
-- SCRIPT: TABLAS PARA ENCUESTAS INTERACTIVAS
-- ==========================================

-- 1. Crear tabla de Votos en Encuestas
CREATE TABLE IF NOT EXISTS public.post_poll_votes (
    id bigint generated by default as identity primary key,
    post_id bigint not null references public.posts(id) on delete cascade,
    user_id bigint not null references public.users(id) on delete cascade,
    option_index integer not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Asegurarse de que un usuario solo pueda votar una vez por post
ALTER TABLE public.post_poll_votes
ADD CONSTRAINT unique_post_user_vote UNIQUE (post_id, user_id);

-- Configurar RLS
ALTER TABLE public.post_poll_votes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'post_poll_votes' AND policyname = 'Lectura publica de votos'
    ) THEN
        CREATE POLICY "Lectura publica de votos" ON public.post_poll_votes FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'post_poll_votes' AND policyname = 'Usuarios insertan sus votos'
    ) THEN
        CREATE POLICY "Usuarios insertan sus votos" ON public.post_poll_votes FOR INSERT WITH CHECK (true);
    END IF;
END
$$;
