-- Script para agregar lógica de planes individuales en AgroSmart
-- Por favor, ejecuta este script en el SQL Editor de tu panel de Supabase.

-- 1. Asegurar que la tabla 'users' tenga la columna 'plan'
-- Si la columna ya existe, esto simplemente lanzará un aviso.
ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS plan TEXT DEFAULT 'none';

-- 2. Asegurarse de que el 'plan' individual tenga un comentario explicativo
COMMENT ON COLUMN public.users.plan IS 'Plan individual del usuario. Puede ser: none, bronce, platinium, diamante, esmeralda. Sobrescribe el plan del país si no es none.';

-- 3. (Opcional) Si decides usar un trigger o RLS basándote en el plan, asegúrate de que el schema cache se actualice.
NOTIFY pgrst, 'reload schema';

-- 4. Nueva tabla para Noticias Globales (El Super Niño y crisis climáticas)
CREATE TABLE IF NOT EXISTS public.global_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    image_url TEXT,
    source TEXT DEFAULT 'Global Env Watch',
    severity TEXT DEFAULT 'normal', -- 'normal', 'warning', 'critical'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS pero permitir lectura a todos los usuarios autenticados
ALTER TABLE public.global_news ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    DROP POLICY IF EXISTS "Todos pueden leer noticias" ON public.global_news;
EXCEPTION WHEN OTHERS THEN END $$;

CREATE POLICY "Todos pueden leer noticias" ON public.global_news
    FOR SELECT USING (auth.role() = 'authenticated');

-- Permitir que cualquier usuario inserte (ya que nuestro bot de JS insertará las simulaciones)
DO $$ BEGIN
    DROP POLICY IF EXISTS "Todos pueden insertar noticias" ON public.global_news;
EXCEPTION WHEN OTHERS THEN END $$;

CREATE POLICY "Todos pueden insertar noticias" ON public.global_news
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Permitir eliminar para limpieza manual/JS
DO $$ BEGIN
    DROP POLICY IF EXISTS "Todos pueden eliminar noticias" ON public.global_news;
EXCEPTION WHEN OTHERS THEN END $$;

CREATE POLICY "Todos pueden eliminar noticias" ON public.global_news
    FOR DELETE USING (auth.role() = 'authenticated');

-- 5. Función y Trigger para auto-eliminar noticias de más de 7 días
-- Al insertar una nueva noticia, el trigger revisará y borrará las viejas automáticamente
CREATE OR REPLACE FUNCTION public.cleanup_old_global_news()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM public.global_news WHERE created_at < NOW() - INTERVAL '7 days';
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_cleanup_old_global_news ON public.global_news;
CREATE TRIGGER trigger_cleanup_old_global_news
    AFTER INSERT ON public.global_news
    FOR EACH STATEMENT
    EXECUTE FUNCTION public.cleanup_old_global_news();

NOTIFY pgrst, 'reload schema';
